bias: 0.1
case: wecap
colors:
- - - 0.8901960784313725
    - 0.10196078431372549
    - 0.10980392156862745
  - - 0.984313725490196
    - 0.6039215686274509
    - 0.6
- - - 0.12156862745098039
    - 0.47058823529411764
    - 0.7058823529411765
  - - 0.6509803921568628
    - 0.807843137254902
    - 0.8901960784313725
- - - 1.0
    - 0.4980392156862745
    - 0.0
  - - 0.9921568627450981
    - 0.7490196078431373
    - 0.43529411764705883
- - - 0.41568627450980394
    - 0.23921568627450981
    - 0.6039215686274509
  - - 0.792156862745098
    - 0.6980392156862745
    - 0.8392156862745098
corrlength: 0
figformat: pdf
livetime: 2.154434690031884
livetimes:
- 0.01
- 0.021544346900318832
- 0.046415888336127774
- 0.1
- 0.21544346900318834
- 0.46415888336127775
- 1.0
- 2.154434690031884
- 4.641588833612778
- 10.0
- 21.544346900318832
- 46.41588833612777
- 100.0
local:
  local: /home/katrin/Documents
  path_pksflare: /home/katrin/Documents/nuisance_summary/PKS_flare
magnitude: 0
model: crab_log
norm: 0.1
parameter_names:
- - amplitude
  - alpha
- - amplitude
  - beta
- - beta
  - alpha
resolution: 0
source: PKSflare
sys: Combined
tilt: 0.02
wecap:
  path: /home/vault/caph/mppi062h/repositories/HESS_3Dbkg_syserror/2-error_in_dataset
  path_pksflare: /home/wecapstor1/caph/mppi045h/nuisance_summary/PKS_flare
woody:
  path: /home/vault/caph/mppi062h/repositories/HESS_3Dbkg_syserror/2-error_in_dataset
  path_pksflare: /home/hpc/caph/mppi045h/3D_analysis/N_parameters_in_L/nuisance_summary/Crab
zero: 1.0e-12
